# A sample Gemfile
source "https://rubygems.org"

gem 'sinatra'

# Twilio
gem 'twilio-ruby'
gem 'jwt', '<=1.2'

# Sequel-sinatra
gem 'sequel'
gem 'sinatra-sequel'
gem 'pg'

# Config
gem 'sinatra-contrib'

# Openssl
gem 'openssl'

group :test, :development do
  gem 'rspec'
  gem 'capybara'
end

group :test do
  gem 'rake'
  gem 'rack-test'
end
